### ISSUE TITLE
The ftc local planner can't work with hector_mapping together

### ISSUE THREAD

**Issue by drscopus** [asr-ros/asr_ftc_local_planner#1]
My question has been asked in [answers.ros.org](http://answers.ros.org/question/266759/the-new-path-planner-cant-work-with-hector_mapping-together/). 
We have tried different global planner and mapping method. 
It seems that ftc_local_planner  can be used with[ hector mapping](http://wiki.ros.org/hector_mapping).

Looking fowards to any valuable advices. Thanks!

**Comment by drscopus** [comment]
The generated map by hector mapping is with 0.05m Resolution. The generated map is saved with size 256X256. So the size of global map is also with size 256X256.

With a know map(withou hectormap), using amcl and move_base, there are almost no warning in the terminal, the robot moves normally, although it often pauses.

The update frequency of globla costmap and local costmap is 3Hz. The controll frequency of move base is also 3hz

The parameters of ftc are
```

FTCPlanner:
  max_x_vel: 0.35
  max_rotation_vel: 1.0
  min_rotation_vel: 0.4
  acceleration_x: 0.35
  acceleration_z: 0.5
  position_accuracy: 0.05
  rotation_accuracy: 0.03
  slow_down_factor: 2.5
  sim_time: 0.75
  local_planner_frequence: 3
  join_obstacle: false
```
Looking forwards to your valuable advices. Thanks
